---
- hosts: RedHat Debian
  remote_user: ansible
  become: yes
  become_method: sudo

  roles:
  - role: apache-RedHat
    when: ansible_facts['os_family'] == "RedHat"
  - role: apache-Debian
    when: ansible_facts['os_family'] == "Debian"
